name: DevOps Assignment CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run containers
        run: |
          docker compose up --build -d

      - name: Wait for services
        run: sleep 15

      - name: Test Service A
        run: curl http://localhost:5000/health

      - name: Check Service B logs
        run: docker logs $(docker ps -q --filter "name=service-b")

      - name: Stop containers
        run: docker compose down
